spring:
   datasource:
      username: hh_finder
      password: hh_finder
      url: jdbc:mysql://localhost:3306/hh_finder
      
   jpa:
      hibernate:
         ddl-auto: update 
      show-sql: true
      properties:
         hibernate:
            format_sql: true
      defer-datasource-initialization: true
      
   sql:
      init:
         mode: always